export {default as Busride} from "./Busride/Busride";
export {default as Contact} from "./Contact/Contact";
export {default as Footer} from "./Footer/Footer";
export {default as Hero} from "./Hero/Hero";
export {default as Media} from "./Media/Media";
export {default as Navbar} from "./Navbar/Navbar";
export {default as News} from "./News/News";
export {default as About} from "./About/About";
export {default as Production} from "./Production/Production";
